name: Build & Update Quilt Minecraft Mod for 1.21.7

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Update Minecraft version to 1.21.7
        run: |
          sed -i 's/minecraft\s*=\s*".*"/minecraft = "1.21.7"/' gradle.properties || true
          sed -i 's/minecraft\s*=\s*".*"/minecraft = "1.21.7"/' build.gradle || true
          # If Quilt version is specified elsewhere, update similarly

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build mod
        run: ./gradlew build

      - name: Upload mod jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: quilt-mod-jar
          path: |
            build/libs/*.jar
